"""Add language to posts

Revision ID: 443cfd112350
Revises: 033885979439
Create Date: 2019-09-06 18:12:58.570644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443cfd112350'
down_revision = '033885979439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
